### ISSUE TITLE
Leaflet.extras addSearchFeatures not rendering

### ISSUE THREAD

**Issue by AMoss22** [trafficonese/leaflet.extras#143] opened 2018-05-24 16:24 UTC

**Comment by AMoss22** [comment] 2018-05-24 16:30
Hi I used one of your examples to add search feature code below. This runs and produces the map with the search box but when I type in New York (or any of the other city names) it location is not found. Do you have any ideas why this might be. Many thanks 
This is the example I tried

cities <- read.csv(textConnection("City,Lat,Long,Pop
Boston,42.3601,-71.0589,645966
Hartford,41.7627,-72.6743,125017
New York City,40.7127,-74.0059,8406000
Philadelphia,39.9500,-75.1667,1553000
Pittsburgh,40.4397,-79.9764,305841
Providence,41.8236,-71.4222,177994"))
  
  leaflet(cities) %>% addProviderTiles(providers$OpenStreetMap) %>%
    addCircleMarkers(lng = ~Long, lat = ~Lat, weight = 1, fillOpacity=0.5,
                     radius = ~sqrt(Pop)/50 , popup = ~City, label=~City, group ='cities') %>%
    addResetMapButton() %>%
    addSearchFeatures(
      targetGroups = 'cities',
      options = searchFeaturesOptions(
        zoom=12, openPopup = TRUE, firstTipSubmit = TRUE,
        autoCollapse = TRUE, hideMarkerOnCollapse = TRUE )) %>%
    addControl("<P><B>Hint!</B> Search for ...<br/><ul><li>New York</li><li>Boston</li><li>Hartford</li><li>Philadelphia</li><li>Pittsburgh</li><li>Providence</li></ul></P>",
               position='bottomright')

**Comment by schloerke** [comment] 2018-06-08 14:15
The circle marker issue looks to be fixed without testing.

https://github.com/stefanocudini/leaflet-search/issues/196 is not fixed as Path has not removed.

Once Path is removed, I'll make a PR.

**Comment by ramnathv** [comment] 2018-06-08 15:42
Thanks for the update @schloerke!

**Comment by tim-salabim** [comment] 2018-06-08 16:09
For what it's worth, @ramnathv I can confirm @schloerke 's comment. About two weeks ago I updated a local clone of leaflet.extras to the latest version of leaflet-search and still had to remove the Path bit to get it working properly.

**Comment by AMoss22** [comment] 2018-07-24 10:48
Thank you all for your comments, I'm a bit confused what I have to do to get this function to work.  It clearly works in the Rpubs example.  I am using R studio version 1.1.183, R version 3.4.2, leaflet version 2.0.1 and leaflet.extras version 1.0.0.  I have tried to compare the html but it is very different.  
Any help would be appreciated

**Comment by erstearns** [comment] 2018-07-27 09:38
I am also having the same issue with all three addSearch options. addSearchUSCensusBureau and addSearchOSM result in the search icon being present on the leaflet map, however addSearchGoogle does not.  Also puzzled by the fact that it is working great in the Rpubs example. I am running RStudio version: 1.1.456, R version: 3.4.4, leaflet version 2.0.1.9 and leaflet.extras version 1.0.0. Not sure what could be driving the issue, but wanted to contribute information on my system to help diagnose the problem.

**Comment by mhaditama26** [comment] 2018-08-28 05:57
The feature you added has to have a label..
thus you can search it 

> addMarkers(yourfeature$Longitude, yourfeature$Latitude, **label=**yourfeature$name,popup = yourfeature$name,  group = "yourfeature")%>%

**Comment by yzjiangyang** [comment] 2018-08-29 07:12
@tim-salabim, how to remove the Path bit to get it working properly? leaflet extra Search Button does not work for me either.

**Comment by ryanscharf** [comment] 2018-10-17 18:03
This still appears to be a problem with leaflet 2.0.2 and leaflet.extras 1.0.0.  It seems to be recognized that CircleMarkers don't work, but I haven't been able to get the RPubs addSearchFeatures() example to work with addCircles() either.

**Comment by bhaskarvk** [comment] 2018-11-01 15:40
I'll be resuming development of leaflet.extras in Dec and will tackle this in that round. Thanks!

**Comment by yzjiangyang** [comment] 2018-11-07 18:09
@bhaskarvk 
How Can we remove the path to make CircleMarkers search button work properly?
Thanks

**Comment by yzjiangyang** [comment] 2018-12-01 02:40
> I'll be resuming development of leaflet.extras in Dec and will tackle this in that round. Thanks!

@bhaskarvk Hi, Will you work on the leaflet search button in Dec? Thank you

**Comment by TacticalFate** [comment] 2018-12-29 03:20
I figured out how to make the search work with the CircleMarkers (removing the path check), you have to go into your R library path 
#R Library path#\leaflet.extras\htmlwidgets\build\lfx-search\

Open lfx-search-prod.js and search for "e instanceof t.Path ||" , and then delete it. Your CircleMarker search should work now

**Comment by ryanscharf** [comment] 2019-01-03 17:02
@TacticalFate Are you editing the package files?  Those directories don't exist for me.

**Comment by Vicellken** [comment] 2019-02-25 09:23
> I figured out how to make the search work with the CircleMarkers (removing the path check), you have to go into your R library path
> #R Library path#\leaflet.extras\htmlwidgets\build\lfx-search\
> 
> Open lfx-search-prod.js and search for "e instanceof t.Path ||" , and then delete it and save the file. Your CircleMarker search should work now

Thank you! Your solution works for me!

**Comment by trafficonese** [comment] 2024-04-02 10:04
I updated leaflet-search to v4.0.0 and `addSearchFeatures` should be working again.

**Closed by trafficonese** 2024-04-02 10:04 UTC
